### ISSUE TITLE
raster support

### ISSUE THREAD

**Issue by ansis** [mapbox/vector-tile-js#23]
It's not in the spec, but it's in the mapnik-vector-tile implementation: https://github.com/mapbox/mapnik-vector-tile/blob/0c9d7cccfc884181721a88bce00d6b546a73660b/proto/vector_tile.proto#L72

@springmeyer When will this get added to the spec? Are there still any doubts?

**Comment by springmeyer** [comment]
It will be present in the next revision of the spec. Not major doubts and its needed to easily support compositing of vector + raster layers.

**Comment by jfirebaugh** [comment]
I believe we cut raster from VTv2; I don't see it in [2.1](https://github.com/mapbox/vector-tile-spec/tree/master/2.1).

We can revisit when this moves again on the spec side.
