### ISSUE TITLE
remove point-feature

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/vector-tile-js#35]
The use of point-feature and `{ x, y }` objects seems out of place in such a low-level library. Can we switch to `[x, y]` coordinates for 2.0?

**Comment by mourner** [comment]
Two reasons to keep it: 
- `{x, y}` is more performant and takes less memory (apparently V8 reserves more than 2 items for each coordinate internally)
- we need the point abstraction in GL JS, and returning `[x, y]` would force us to add a conversion step in GL JS, along with GC churn

If you view the library separately from GL JS though, it's indeed weird to have a point type. One thing I considered doing is accepting a point factory in the VT constructor (defaulting to `(x, y) => [x, y]`), which may be best of both worlds.

**Comment by jfirebaugh** [comment]
I'm assuming we'd convert gl-js to use `[x, y]` internally, and use the `Point` type only for things like cursor coordinates (if even that).

**Comment by mourner** [comment]
My first point about performance is still valid, and we do a huge ton of coordinate math throughout the code, so rewriting everything for `[x, y]` and static point arithmetic functions would take a big effort.

**Comment by jfirebaugh** [comment]
Profiling issues like https://github.com/mapbox/mapbox-gl-js/issues/5208, the GC pressure from allocating lots of temporary arrays and tiny objects is substantial.

![image](https://user-images.githubusercontent.com/98601/30085999-ee8c6f38-924d-11e7-8527-733d5c58b2f0.png)

I would like to explore an alternate API for v2 based on either ES6 generators or passing in a function to be called for each geometry element (each ring and point). ES6 generators would be more ergonomic, but a callback approach would be more compatible with legacy browsers (IE11) and also avoid the overhead of `Point` allocations (you could pass x and y as individual parameters).

**Comment by mourner** [comment]
-> #79
