### ISSUE TITLE
Distinct polygons erroneously decoded as interior holes of another

### ISSUE THREAD

**Issue by peterqliu** [mapbox/vector-tile-js#36]
Decoding [this buffer](https://a.tiles.mapbox.com/v4/mapbox.mapbox-terrain-v2/14/3074/6421.vector.…token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g) gives me [this geojson](https://gist.github.com/peterqliu/4cec494321b3deb14034) of contour polygons. 

![screen shot 2015-10-10 at 9 08 07 pm](https://cloud.githubusercontent.com/assets/4551508/10414620/befc764e-6f92-11e5-9b0e-d612fbd554c7.png)

Filtering this featurecollection for geometries matching the property `ele=700` gives me [this subset of features](https://gist.github.com/peterqliu/9019d4090751b7fb63a2) (still geojson):

![screen shot 2015-10-10 at 9 08 33 pm](https://cloud.githubusercontent.com/assets/4551508/10414621/c4c77056-6f92-11e5-811e-7c5913004ffd.png)

However, the above featurecollection has only two features: one for the large mass to the east, and a second that specifies the three slivers to the west as two holes within a third shape. 

![screen shot 2015-10-10 at 9 12 45 pm](https://cloud.githubusercontent.com/assets/4551508/10414632/63ca0952-6f93-11e5-8609-7a8d50414ceb.png)

The three shapes clearly don't overlap, and should be distinct polys of their own.

**Comment by jfirebaugh** [comment]
Can you try out the [`classify-rings`](https://github.com/mapbox/vector-tile-js/tree/classify-rings) branch and see if it produces reasonable results (either four `Polygon`s or one `MultiPolygon`)?

**Comment by peterqliu** [comment]
:+1: `Multigon` achieved with that branch.
