### ISSUE TITLE
Possibly duplicating features

### ISSUE THREAD

**Issue by peterqliu** [mapbox/vector-tile-js#41]
Decoding [this buffer](https://a.tiles.mapbox.com/v4/danpat.osrmdbg-edges/19/83856/202693.vector.pbf?access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g) gives me [this geojson](https://gist.github.com/peterqliu/b3a2e166c24888e46ac4), with many features identically duplicated. 

@danpat is fairly confident that none of the features were duplicated when he baked the tileset, so I'm wondering if this is happening in vt-js

cc @jfirebaugh @mourner

**Comment by danpat** [comment]
@peterqliu I tracked down some of the original GeoJSON for this (s3://mapbox/playground/danpat/24h-traffic-1/1400/1447454472-debug.geojson.gz)

There are duplicates in that, looks like a bug on my end, not `vector-tile-js`

Closing.
