### ISSUE TITLE
.toGeoJSON() returning [null,null] coordinate pairs

### ISSUE THREAD

**Issue by wboykinm** [mapbox/vector-tile-js#42]
. . . when using the mapbox-streets-v6 endpoint as a source, the `.toGeoJson` method returns all null coordinate pairs from a decoded `.pbf`. All non-geom properties are decoded and written correctly.

### Call
```js
    var buf = new Protobuf(body);
    var vt = new VectorTile(buf);
    var layer = vt.layers['water'];
    
    if (layer.length > 0) {
      var waterSet = {"type":"FeatureCollection","features":[]};
      for (var i = 0; i < layer.length; i++) {
        var feature = layer.feature(i).toGeoJSON();      
        waterSet.features.push(feature);
      }
      console.log(JSON.stringify(waterSet));
    }
```

As part of [this script](https://github.com/wboykinm/tribes/blob/master/processing/water/get.js).

### Result

A lot of this:

`. . . {"type":"Polygon","coordinates":[[[null,null],[null,null],[null,null], . . .`

This is the same over several test tiles. [Here's the full response from a tile](https://gist.github.com/wboykinm/56440fc58792390c7f37208feec5b3af).

**Comment by springmeyer** [comment]
Can you provide a testcase that is actually runnable? Rig the testcase to download a single tile, or check the tile into a gist with a test script [similar to this](https://gist.github.com/springmeyer/74a01851c6081b57f92b), or at the least provide a link to one tile that you are seeing this with.

**Comment by jfirebaugh** [comment]
`toGeoJSON` takes three arguments: the tile `x`, `y`, and `z` coordinates. (They aren't included in the tile itself.)

**Comment by wboykinm** [comment]
@jfirebaugh I've gotten the same result with the tile address included as well.

@springmeyer I'll put up a runnable test today.

**Comment by wboykinm** [comment]
@springmeyer [Here's a replicable test](https://gist.github.com/wboykinm/0d87f55caa301924e924d7c02d330e25); thanks for taking a look.

**Comment by springmeyer** [comment]
Thanks @wboykinm. I replicated and fixed by doing:

```diff
- var feature = layer.feature(i).toGeoJSON(x + ',' + y + ',' + z); 
+ var feature = layer.feature(i).toGeoJSON(x,y,z);
```

So you need to pass in three ints rather than an xyz string. Looks like `toGeoJSON` should validate its input rather than create garbage on string input: https://github.com/mapbox/vector-tile-js/blob/40f73eb2c417979601be973e046e169c74147ca7/lib/vectortilefeature.js#L129

**Comment by springmeyer** [comment]
Btw @wboykinm - the water layers with no features will be fixed in upcoming streets renders. The mapnik-vt encoder recently was changed to drop encoding layers when no features are present.

**Comment by wboykinm** [comment]
![louie_facepalm](https://cloud.githubusercontent.com/assets/735463/14414130/823ca8e2-ff5b-11e5-9f09-9d4547042d5a.gif)

Ugh - sorry for the false alarm based on my JS type confusion. Thanks for looking at it!
