### ISSUE TITLE
`id` should be a public property

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/vector-tile-js#43]
Currently feature IDs are [read into an `_id` property](https://github.com/mapbox/vector-tile-js/blob/40f73eb2c417979601be973e046e169c74147ca7/lib/vectortilefeature.js#L23), implying that the property is not part of the public API. But IDs are part of the vector tile specification, and there is no reason to keep this property private. It should be accessible via a non-underscore-prefixed accessor.

**Comment by drnextgis** [comment]
I've faced with this limitation working with OpenLayers 3 https://github.com/openlayers/ol3/issues/5366
