### ISSUE TITLE
Throw nicer error when tiles are missing geometry

### ISSUE THREAD

**Issue by danpat** [mapbox/vector-tile-js#47]
I created some tiles that had features, but no geometry.

This causes `vector-tile-js` to throw on this line:

https://github.com/mapbox/vector-tile-js/blob/master/lib/vectortilefeature.js#L122

This error is a bit misleading, because invalid bytes are being interpreted.  We should instead throw "No geometry field found".  Strictly speaking, we're incorrectly parsing the PBF data stream here.

**Comment by jfirebaugh** [comment]
Duplicate of #39.
