### ISSUE TITLE
Unimplemented type: 4

### ISSUE THREAD

**Issue by apollolm** [mapbox/vector-tile-js#5]
Hello.  Thanks for sharing this!  I'm using vector-tile-js to decode .pbfs on the client and draw in a Leaflet canvas layer.  These are being served using PGRestAPI (https://github.com/spatialdev/PGRestAPI) both from pre-created .mbtiles files from TileMill2, and/or dynamically from PostGIS or Shapefiles.  Most of the datasources I've tried have worked great, until just now.  I loaded a global administrative boundary layer (GADM) into TileMill2, tiled it up, and am serving it up.  I'm getting Unimplemented type: 4 in Protobuf.prototype.skip. 

This seems to correspond to features probably with complicated geometries (maybe multipolygons - islands?), which in this dataset is happening mostly along coastlines.

![screen shot 2014-05-30 at 3 06 52 pm](https://cloud.githubusercontent.com/assets/144543/3136834/b0233848-e847-11e3-8417-977de96bee22.png)

...Notice most of the country's coastal districts are missing.

Zooming in to Daytona Beach - the tiles that are conspicuously missing actually have tiny little features drawn in them:
![screen shot 2014-05-30 at 3 16 43 pm](https://cloud.githubusercontent.com/assets/144543/3136861/280cc7d4-e848-11e3-951c-ca9e2ac68343.png)

I am using deflate on the server when serving up the .pbfs, and, as I said, I'm not having any problems with other polygon, line or point feature types.

![screen shot 2014-05-30 at 3 20 04 pm](https://cloud.githubusercontent.com/assets/144543/3136905/f9e68a6a-e848-11e3-9e53-603f6618a961.png)

Any thoughts?  
Thanks,
Ryan

**Comment by jfirebaugh** [comment]
Sounds like this was a result of passing non-PBF data in -- closing.
