### ISSUE TITLE
Typo in VectorTileFeature.js for Point type?

### ISSUE THREAD

**Issue by createthis** [mapbox/vector-tile-js#53]
I was working on a script that turns geojson-vt JSON tiles back into GeoJSON files today. I noticed my points were coming out null and I had used vectortilefeature.js's toGeoJSON() method as a base for my code.

Is this a typo?

https://github.com/mapbox/vector-tile-js/blob/5c453951e1a28fdfbf37f2b4535cab00125a6106/lib/vectortilefeature.js#L151

For me, changing:
```javascript
points[i] = coords[i][0];
```

to:
```javascript
points[i] = coords[i];
```

solved the problem. It's possible this is some quirk of geojson-vt or my code causing the problem, but I thought I would ask just in case it's a bug.

**Comment by springmeyer** [comment]
Thanks for reporting. I'm also not sure if this is a bug or not on first glance. I see @jfirebaugh added this code in https://github.com/mapbox/vector-tile-js/commit/c16b5c0d592f69f96c8a3bed23ebcdd81b6b49b1 to account for multi geometries better. @createthis can you provide a testcase that shows the problem?

**Comment by jfirebaugh** [comment]
I believe the code is correct as written. The [vector tile specification](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/README.md#4342-point-geometry-type) says that a point geometry is encoded as a MoveTo command with a command count greater than 0. This will be decoded by `VectorTileFeature.prototype.loadGeometry` as an array of single element arrays, each containing one `Point`.  Thus `coords[i][0]` is the correct way to extract the _i_ th `Point` in the geometry.

**Comment by createthis** [comment]
It's probably a quirk of geojson-vt then. Thanks.
