### ISSUE TITLE
What is the role of vector tile serialization?

### ISSUE THREAD

**Issue by erande** [mapbox/vector-tile-js#57]
Please look at the questions in the picture.

![capture](https://user-images.githubusercontent.com/15340497/29307734-e08f343a-8157-11e7-9892-f46256b4272f.PNG)

Thanks,
Alice

**Comment by jfirebaugh** [comment]
Sorry Alice, I don't understand the question. There's not really a data pipeline as you've diagrammed it. This library decodes a vector tile PBF into a Javascript representation.
