### ISSUE TITLE
High GC activity from readUtf8 when using vector-tile

### ISSUE THREAD

**Issue by steve9164** [mapbox/vector-tile-js#58]
Here are some profiling screenshots (from OS X 10.11.6 & Chrome Version 60.0.3112.113):
![image](https://user-images.githubusercontent.com/13863530/29852006-e4e2a164-8d7a-11e7-8fd2-4439e4824aed.png)
![image](https://user-images.githubusercontent.com/13863530/29852015-f59951b0-8d7a-11e7-9984-20870633c4a2.png)

It looks like building the string using concatenation of char codes is causing the GC activity. This is more of a problem with layers that have long property strings on features.

**Comment by jfirebaugh** [comment]
Hey @steve9164, thanks for the report. Do you have an idea for how this could be improved? The code you've screenshotted is from [the pbf module](https://github.com/mapbox/pbf/blob/6deeabcd60c2e900bb216dec0f3e210347eb923c/index.js#L501-L562), not vector-tile-js. If there's an optimization possible, that's where we would make it -- we'd welcome a PR there.
