### ISSUE TITLE
Use id property as feature id if not exist.

### ISSUE THREAD

**Issue by Asteb612** [mapbox/vector-tile-js#69]
The goal is to use MVT tile generated by `ST_AsMVT` function on postgis 2.4 and  2.5.
Because feature id is not provided mapbox-gl throw this error :
`Error: The feature id parameter must be provided.`

Today the solution i found is to make this modification directly on sources and rebuild mapboxgl :

```
diff --git a/lib/vectortilefeature.js b/lib/vectortilefeature.js
index b9880a1..474fdfd 100644
--- a/lib/vectortilefeature.js
+++ b/lib/vectortilefeature.js
@@ -17,6 +17,10 @@ function VectorTileFeature(pbf, end, extent, keys, values) {
     this._values = values;
 
     pbf.readFields(readFeature, this, end);
+
+    if ('id' in this.properties && !this.id) {
+       this.id = this.properties.id;
+    }
 }
```
I think this modification can be useful to some people that can't update postgis to 3.0 version.

**Comment by Asteb612** [comment]
I have created a issue because i don't have se access right to create a pull request.

**Comment by mourner** [comment]
We can't really do that because Vector Tile Spec v2 does not support string ids, while property values can be strings. However, Mapbox GL JS v1.7.0 has a feature that makes this unnecessary — `promoteId`, see https://github.com/mapbox/mapbox-gl-js/pull/8987
