### ISSUE TITLE
cannot find source-Layer Ids after reading Vector Tile using vector-tile JS library

### ISSUE THREAD

**Issue by dksivagis** [mapbox/vector-tile-js#73]
Hi ,
I took a vector tile to read the Layer and its corresponding features.

I found 

- My layer is "Landuse"
- I found all the features that are inside the "Landuse" Layer.

I know that some of the features belong to Cemetry, Education etc..

**The problem is , i am not able to find the ID of each feature like its been represented in the StyleSheet.** 

With out the "id", i cannot cannot seperate and display my features with in "landuse" layer

Here is one sample from the style sheet
```
 "id": "landuse_cemetery",
            "source": "orgVector",
            "source-layer": "landuse",
            "type": "fill",
            "minzoom": 11
```
My question is how to get the "id" along with features?
Please help me if i am missing some thing while reading the MVT tile.

**Comment by vicb** [comment]
Have you looked at the properties of your features ? 
Try `console.log(feature.properties);`
