### ISSUE TITLE
How convert to longitude and latitude geojson?

### ISSUE THREAD

**Issue by houxieyu** [mapbox/vector-tile-js#75]
I use VectorTileFeature.toGeoJSON method,but the result position is relative coordinate.
How create   longitude and latitude geojson data?

**Comment by adamochayon** [comment]
@houxieyu Make sure to call `toGeoJSON` with the tile coordinates.
Something like this should work:
`layer.feature(i).toGeoJSON(x, y, z)`

**Comment by mmomtchev** [comment]
What if the extent is not the world extent?
