### ISSUE TITLE
Package activity and contributions

### ISSUE THREAD

**Issue by adamochayon** [mapbox/vector-tile-js#76]
Hey @mourner, @anandthakker!
First of all - Thank you for your work in the package (and on the entire suite of packages and tools around it).

I have noticed the package has not been actively maintained in the past couple of years and would like to know:
- Is it still the most relevant package for loading MVTs in node / JS?
- Assuming it is - I have some ideas for some small enhancements (such as adding a `_tags` to `VectorTileFeature`, adding `toJSON`, etc). What would you suggest is the best way to handle them? I could fork the package but would rather have the enhancements more widely available.

**Comment by mourner** [comment]
Sorry for not responding at the time. The repo has been revived, with [v2.0](https://github.com/mapbox/vector-tile-js/releases/tag/v2.0.0) released now, and v3.0 in plans described in #79.

For small enhancements, it's worth submitting issues for them for discussion. Generally, we try to keep libraries as minimal and simple as possible to make maintenance easier.
