### ISSUE TITLE
dist file folder

### ISSUE THREAD

**Issue by prasanjitdash** [mapbox/vector-tile-js#77]
I am not familiar with building packages (using grunt etc) and do not have the setup to try it. I would like to use `vector-tile-js` as a dependency for another package: `leaflet.vectorGrid-1.3.0` Can you please provide the /dist file that can be directly used? Thanks

**Comment by mourner** [comment]
Sorry for not responding earlier. NPM provides the distribution files, they aren't meant to be included in the repo itself.
