### ISSUE TITLE
Deserialization of properties

### ISSUE THREAD

**Issue by guimochila** [mapbox/vector-tile-js#82]
I am facing some issue regarding deserialization of the property `properties` in features. Objects in the property `properties` are not being deserialized properly. Please, see https://github.com/maplibre/maplibre-gl-js/issues/1325

Is this by design? It would be nice if deserialization had the same output as before serialization.

Thanks in advance.

**Comment by mourner** [comment]
This is unfortunately by design, because the current Vector Tile Specification doesn't allow encoding nested values — see the definition here: https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L17-L25
